name: RSS Auto Update

on:
  schedule:
    - cron: '0 * * * *'  # 毎時0分に実行
  workflow_dispatch:     # 手動実行も可能

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: node scripts/generate-rss-html.js
      - run: git config user.name github-actions
      - run: git config user.email github-actions@users.noreply.github.com
      - run: git commit -am "Auto update RSS HTML" || echo "No changes to commit"
      - run: git push
